set(CMAKE_SYSTEM_NAME Darwin)
set(EXTENSION_PLATFORM "macosx_x86_64")

LIST(APPEND CMAKE_PROGRAM_PATH ${CMAKE_SOURCE_DIR}/cross/osx64/bin)

set(CMAKE_C_COMPILER o64-clang)
set(CMAKE_CXX_COMPILER o64-clang++)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SOURCE_DIR}/cross/osx64)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
