#ifndef __com_github_dennisfrancis_xdatacluster_idl__
#define __com_github_dennisfrancis_xdatacluster_idl__

#include <com/sun/star/uno/XInterface.idl>

module com { module github { module dennisfrancis {

    interface XDataCluster : com::sun::star::uno::XInterface
    {
        sequence< sequence< double > > gmmCluster(
            [in] sequence < sequence < double > > data,
            [in] any numClusters,
            [in] any numEpochs,
            [in] any numIterations);
    };

}; }; };

#endif
